name: Build and Deploy

on:
  push:
    branches: [ "master","develop"]
  pull_request:
    branches: [ "master","develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript,typescript     
          

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          

      - name: Build with NPM and Maven
        run: |
          npm install -g @angular/cli
          npm install typescript@2.7.2 --save-dev
          npm install
          npm run build
          mvn clean install
          
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript,typescript 
     
      
      - name: Create WAR file 
        run: mvn -B package --file pom.xml
        
      
      - name: Upload WAR file as artifact
        uses: actions/upload-artifact@v2 
        with:
             name: Schedular-UI
             path: target/schedulerui-v1.0.war        
        
